---
- name: 1. install unzip helper
  apt: name=unzip state=present

- name: 2. creates target directory
  file:
    path: /opt/flask
    state: directory

- name: 3. unzip the files
  unarchive:
    src: flask.zip
    dest: /opt/flask

- name: 4. change initdb.py to be executable
  file: dest=/opt/flask/initdb.py mode=+x

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: install pip
  command: python /tmp/get-pip.py

- pip:
    name: redis

- pip:
    name: flask

- pip:
    name: flask-sqlalchemy

- pip: 
    name: flask_marshmallow

- pip:
    name: pymysql
- name: 5. run initdb.py 
  command: python /opt/flask/initdb.py
