---
- name: 1. install unzip helper
  apt: name=unzip state=present

- name: 2. creates target directory
  file:
    path: /opt/flask
    state: directory

- name: 3. unzip the files
  unarchive:
    src: flask.zip
    dest: /opt/flask

- name: 4. change initdb.py to be executable
  file: dest=/opt/flask/initdb.py mode=+x

- name: 5. run initdb.py
  command: python /opt/flask/initdb.py

- name: run flask detached from terminal
  command: python /opt/flask/app.py </dev/null &>/dev/null &
